apiVersion: apps/v1
kind: Deployment
metadata:
  name: arm64-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arm64-app
  template:
    metadata:
      labels:
        app: arm64-app
    spec:
      containers:
        - name: arm64-app
          image: nginx:1.25.3-alpine
          resources:
            requests:
              cpu: 500m
      nodeSelector:
        kubernetes.io/arch: arm64
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64